services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - fintech-net

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - fintech-net
    # We will add 'depends_on' and 'environment' for the backend tomorrow

  db:
    image: postgres:14-alpine
    # Use the variables from the .env file
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      # Map the named volume to the container's data directory
      - db-data:/var/lib/postgresql/data
    networks:
      - fintech-net

networks:
  fintech-net:
    driver: bridge

# This is the new top-level key to declare the named volume
volumes:
  db-data:
